# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.3-stretch
    working_directory: /go/src/github.com/utopia-planitia/utopiactl/
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install software-properties-common
      - run: sudo add-apt-repository ppa:ansible/ansible -y
      - run: sudo sh -c 'echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" > /etc/apt/sources.list.d/ansible-ubuntu-ansible-disco.list'
      - run: sudo apt-get update
      - run: sudo apt-get install ansible --allow-unauthenticated
      - checkout
#      - run: go get -v -t -d ./...
      - run: go test -v ./...
